package ai.sovereignrag.core.chat.strategy

import ai.sovereignrag.chat.domain.ChatSession
import ai.sovereignrag.config.SovereignRagProperties
import ai.sovereignrag.domain.SearchResult

/**
 * Strategy interface for handling different types of chat interactions
 *
 * Each implementation handles a specific type of response scenario
 * (e.g., KB-based, general knowledge, identity query, etc.)
 */
interface ChatResponseStrategy {

    /**
     * Check if this strategy can handle the given context
     *
     * @param context Complete context for the chat interaction
     * @return true if this strategy should be used for this context
     */
    fun canHandle(context: ChatContext): Boolean

    /**
     * Priority for strategy selection (higher = checked first)
     *
     * Used when multiple strategies could handle the same context.
     * Default priority is 0 (lowest).
     */
    fun priority(): Int = 0

    /**
     * Generate response using this strategy
     *
     * @param context Complete context for the chat interaction
     * @return ChatResponse containing the generated response and metadata
     */
    fun generateResponse(context: ChatContext): ChatResponse
}

/**
 * Context object containing all inputs needed for response generation
 *
 * Encapsulates all data strategies need to make decisions and generate responses.
 */
data class ChatContext(
    val session: ChatSession,
    val message: String,
    val effectiveLanguage: String?,
    val languageInstruction: String,
    val isIdentityQuery: Boolean,
    val searchResults: List<SearchResult>,
    val hasHighQualityResults: Boolean,
    val useGeneralKnowledge: Boolean,
    val showGkDisclaimer: Boolean,
    val gkDisclaimerText: String?,
    val showSources: Boolean,
    val properties: SovereignRagProperties
)

/**
 * Response generated by a strategy
 *
 * Contains the response text and associated metadata.
 */
data class ChatResponse(
    val response: String,
    val sources: List<String>,
    val needsConfidenceExtraction: Boolean = false, // Whether response contains [CONFIDENCE: XX%] tag
    val shouldLogAsUnanswered: Boolean = false, // Whether this should be logged as unanswered
    val usedGeneralKnowledge: Boolean = false
)
