package ai.sovereignrag.commons.exception

enum class ExceptionCodeEnum(private val message: String) {
    AN_ERROR_OCCURRED("PROCESSING-ERROR-1000"),

    TWO_FACTOR_REQUIRED("TWO-FACTOR-REQUIRED-1001"),

    ID_INFORMATION_REQUIRED("ID-INFORMATION-REQUIRED-1003"),

    SUCCESSFUL("PROCESSED-SUCCESSFULLY-1004"),

    AUTHENTICATION_FAILED("AUTHENTICATION-FAILED-1005"),

    ACCESS_DENIED("ACCESS-DENIED-1006"),

    INVALID_REQUEST("INVALID-REQUEST-1007"),

    DUPLICATE_RECORD("DUPLICATE-RECORD-1008"),

    RECORD_NOT_FOUND("RECORD_NOT_FOUND-1007"),
}
