-- Update testuser password to 'password123' with correct BCrypt hash
-- Using hash generated by the actual system: $2a$10$Nh3WQ6XxZqYScOFtnkM5IOKmzmV9kPF8mo.elKwBKT6vbD1FiaoQu
UPDATE identity.oauth_users 
SET password = '$2a$10$Nh3WQ6XxZqYScOFtnkM5IOKmzmV9kPF8mo.elKwBKT6vbD1FiaoQu',
    updated_at = CURRENT_TIMESTAMP
WHERE username = 'testuser';