package ai.sovereignrag.ingestion.app.config

import ai.sovereignrag.commons.regional.RegionalDatabaseProperties
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(RegionalDatabaseProperties::class)
class RegionalDatabaseConfiguration
